Repository vallenderlab/MicrobiomeR, pull requests merged in 2018-12, with the labels that each got.

#30 Merge reduced_data-patch to the dev-master.
  DESCRIPTION
  R/correlation-plot.R
  R/data.R
  R/heat-tree.R
  R/metacoder-formatting.R
  R/metacoder.R
  R/palettes.R
  R/utils.R
  data/analyzed_greengenes.rda
  data/analyzed_silva.rda
  data/basic_greengenes.rda
  data/basic_silva.rda
  data/phyloseq_greengenes.rda
  data/phyloseq_silva.rda
  data/raw_greengenes.rda
  data/raw_silva.rda
  man/agglomerate_metacoder.Rd
  man/analyzed_greengenes.Rd
  man/analyzed_silva.Rd
  man/basic_greengenes.Rd
  man/basic_silva.Rd
  man/correlation_plot.Rd
  man/get_color_palette.Rd
  man/get_correlation_plots.Rd
  man/get_heat_tree_plots.Rd
  man/save_correlation_plots.Rd
  man/save_heat_tree_plots.Rd
  man/transformer.Rd
  man/transposer.Rd
  man/which_format.Rd
Labels: Priority: Critical :fire::fire::fire::fire:, Type: Enhancement :heart:, Type: Maintenance :wrench:

#48 Heat tree patch
  DESCRIPTION
  NAMESPACE
  R/correlation-plot.R
  R/heat-tree.R
  R/metacoder.R
  man/get_heat_tree_parameters.Rd
  man/get_heat_tree_plots.Rd
Labels: Priority: High :fire::fire::fire:, Type: Bug :beetle: :beetle: :beetle: :beetle:, Type: Maintenance :wrench:

#50 Added barplot functions and improved alpha diversity functions
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/alpha-diversity.R
  R/barplot.R
  R/palettes.R
  R/phyloseq.R
  man/alpha_diversity_plot.Rd
  man/correlation_plot.Rd
  man/get_alpha_diversity.Rd
  man/get_alpha_diversity_measures.Rd
  man/get_correlation_plots.Rd
  man/get_heat_tree_parameters.Rd
  man/get_heat_tree_plots.Rd
  man/get_phyloseq_obj.Rd
  man/get_plot_limits.Rd
  man/melt_metacoder.Rd
  man/save_barplot.Rd
  man/save_correlation_plots.Rd
  man/save_heat_tree_plots.Rd
  man/scico_palette.Rd
  man/stacked_barplot.Rd
  man/transform_metacoder.Rd
  man/viridis_palette.Rd
  tests/testthat.R
  tests/testthat/test-alpha-diversity.R
  tests/testthat/test-barplot.R
Labels: Priority: Critical :fire::fire::fire::fire:, Status: In Progress :construction: :construction:, Status: Review Needed :eye: :eye:, Type: Feature 🎥

#52 Added ordination plot function (#52)
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/ordination.R
  man/ordination_plot.Rd
  tests/testthat/test-ordination.R
Labels: Priority: High :fire::fire::fire:, Type: Feature 🎥
