Repository vallenderlab/MicrobiomeR, pull requests merged in 2019-01, with the labels that each got.

#54 Enhanced pkgdown setup (#54)
  .gitignore
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/palettes.R
  R/utils.R
  _pkgdown.yml
  man/as_raw_format.Rd
  pkgdown/extra.css
  vignettes/.gitignore
  vignettes/get-started.Rmd
Labels: Status: In Progress :construction: :construction:, Type: Documentation :page_facing_up:

#57 Added .github folder with templates (#57)
  .Rbuildignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Priority: Medium :fire::fire:, Status: Completed :checkered_flag::checkered_flag:, Type: Feature 🎥

#67 Added tests for metacoder, heat trees, correlation plots, phyloseq, and palettes. (#67)
  DESCRIPTION
  NEWS.md
  R/metacoder.R
  R/phyloseq.R
  man/create_phyloseq.Rd
  man/sample_id_filter.Rd
  tests/testthat/test-correlation-plot.R
  tests/testthat/test-heat-tree.R
  tests/testthat/test-metacoder-formatting.R
  tests/testthat/test-metacoder.R
  tests/testthat/test-palettes.R
  tests/testthat/test-phyloseq.R
Labels: Priority: High :fire::fire::fire:, Type: Feature 🎥, Type: Maintenance :wrench:
